package Geo_Portal_R;

public class Geo_Portal {
	public static final String iframe = "IGIS_MapViewer";
	public static final String btn_Layer_Collapse = "//div/a/span/i[@class=\"fa fa-layer-group\"]";
	public static final String btn_Layer_expand = "//body/a/span/i[@class=\"fa fa-layer-group\"]";
    public static final String Layer_panel_on = "//aside[@class=\"layers col-sm-2 modalactive expand-right\"]";
    public static final String Layer_panel_off = "//aside[@class=\"layers col-sm-2 modalinactive collapse-left\"]";
    public static final String btn_Draw_Feature = "//a[@title=\"Activate this tool Draw Point, Line, and Polygon on map\"]";
    public static final String  txt_search_layer   ="//input[@id=\"txt_search_layer\"]";
    public static final String  label_District_layer   ="//span[text()=\"District \"]";
    public static final String  label_National_Capital_layer ="//li[@style=\"display: none;\"]/div/a/span[text()=\"National Capital \"]";
    public static final String  btn_add_layer = "//button[@title=\"Add Layer\"]";
    public static final String ddl_search_layer ="//span[@id=\"select2-data-explorer-select-list-container\"]";
    public static final String  txt_search   ="//input[@type=\"search\"]";
    public static final String  label_Education_Add_Layer_ddm   ="//a[text()=\"Education\"]";
    public static final String  btn_view_in_Geoportal = "//div[@id=\"resource-search\"]/div[2]/div/div/a[text()=\"View in Geoportal\"]";
    public static final String  label_Education_layer   ="//span[text()=\"Education \"]";
    public static final String  btn_information_layer ="//div[@id=\"resource-search\"]/div[2]/div/div/a/i";
    public static final String  label_Education_informationpage   ="//span/a[text()=\"Education\"]";
    public static final String  btn_close_Add_Layer ="//a[@id=\"btnsearch\"]";
    public static final String  dialog_Add_Layer ="//div[@class=\"search-box panel-group ui-draggable ui-draggable-handle collapse\"]";
    public static final String  btn_Remove_Selected_Layer = "//button[@title='Remove Selected Layer']";
    public static final String  label_Taluka_Headquarter_layer   ="//span[text()=\"Taluka Headquarter \"]";
    public static final String  label_message_remove_layer   ="//div[text()=\"Individual layer can not be removed. Do you want to remove entire group of layers?\"]";
    public static final String  btn_ok_Remove_Selected_Layer = "//button[text()=\"OK\"]";
    public static final String  label_Success_message_remove_layer   ="//div[text()=\"Layer Group has been deleted successfully.\"]";
    public static final String  btn_collapse_particular_layer = "//div/li[1]/div[@class=\"x-tree-node-el x-unselectable x-tree-node-expanded\"]";
    public static final String  btn_expand_particular_layer = "//div/li[1]/div/img[1]";
    public static final String  chk_Administrative_All_Layer = "//div/li[2]/div/input";
    public static final String  chk_National_Capital_Layer = "//div/li[2]/ul/li[1]/div[1]/input";
    public static final String  img_National_Capital= "//div[@id=\"OpenLayers_Layer_WMS_106\"]";
    public static final String  btn_Get_Layer_information ="//span[text()=\"Get Layer information\"]";
    public static final String  label_information_window ="//span[text()='Info for Layer \"District\"']";
    public static final String  btn_ok_information ="//button[text()=\"OK\"]";
    public static final String  btn_close_information ="//div[@id=\"ext-gen190\"]";
    public static final String  btn_Zoom_Out ="//li[@class=\"view-config-0\"]/a[@title=\"Zoom out\"]";
    public static final String  btn_Legend ="//li[@class=\"view-config-0\"]/a[@title=\"Legend\"]";
    public static final String  btn_Zoom_In ="//li[@class=\"view-config-0\"]/a[@title=\"Zoom In\"]";
    public static final String  btn_Zoom_Next ="//li[@class=\"view-config-0\"]/a[@title=\"Zoom Next\"]";
    public static final String  btn_Zoom_Previous ="//li[@class=\"view-config-0\"]/a[@title=\"Zoom Previous\"]";
    public static final String  btn_Current_Location ="//li[@class=\"view-config-0\"]/a[@title=\"Current Location\"]";
    public static final String  btn_Clear_selection ="//li[@class=\"view-config-0\"]/a[@title=\"Clear selection\"]";
    public static final String  btn_Zoom_to_Layer_Extent ="//span[text()=\"Zoom to Layer Extent\"]";
    public static final String  label_Scale_Extent_level ="//a[text()=\"1:18000000\"]";
    public static final String  btn_Change_Layer_opacity ="//span[text()=\"Change Layer opacity\"]";
    public static final String  btn_Attribute_Information ="//a/span[text()=\"Attribute Information\"]";
    public static final String  btn_Add_WMS_Service ="//button[@id=\"ext-gen160\"]";
    public static final String  btn_Selet_WMS_Service ="//input[@name=\"ext-comp-1069\"]";
    public static final String  ddl_WMS_Service ="//div[text()=\"Add a New Server...\"]";
    public static final String  btn_Cancel_WMS_Service ="//button[text()=\"Cancel\"]";
    public static final String  dailog_Add_New_Server ="//div[@class=\" x-window x-resizable-pinned\"]/div/div/div/div/span[text()=\"Add new server...\"]";
    public static final String  btn_Close_Add_WMS_Service ="//body/div/div/div/div/div/div[@class=\"x-tool x-tool-close\"]";
    public static final String  btn_close_Available_Layer="//div[@class=\"x-tool x-tool-close\"]";
    public static final String  dialog_Available_Layer="//div[@class=\" x-window x-resizable-pinned\"]";
    public static final String  txt_Search_Map_Service = "//input[@placeholder=\"Map Services\"]";
    public static final String  btn_Search_Map_Service = "//button[@id=\"search_filter\"]";
    public static final String btn_Home = "//a[text()=\"Home\"]";
    public static final String lnk_Ebook_Services = "//a[text()=\"Ebook Services\"]";
    public static final String lnk_Atlas = "//a[text()=\"Atlas\"]";
    public static final String lnk_Atlas_of_Agricultural_Resources = "//a[text()=\"Atlas of Agricultural Resources\"]";
    public static final String btn_Flip_Right = "//button[@title=\"Flip right\"]";
    public static final String btn_Flip_Left = "//button[@title=\"Flip left\"]";
    public static final String label_Page_No = "//span[@class=\"BRcurrentpage\"]";
    public static final String btn_one_page_view = "//button[@title='One-page view']";
    public static final String one_page_view = "//div[@class=\"ui-full br-ui-full BookReader no-touch BRmode1up\"]";
    public static final String btn_two_page_view = "//button[@title='Two-page view']";
    public static final String two_page_view = "//div[@class=\"ui-full br-ui-full BookReader no-touch BRmode2Up\"]";
    public static final String btn_thumbnail_view = "//button[@title='Thumbnail view']";
    public static final String thumbnail_view = "//div[@class=\"ui-full br-ui-full BookReader no-touch BRmodeThumb\"]";
    public static final String btn_zoom_in = "//button[@title=\"Zoom in\"]";
    public static final String btn_zoom_out = "//button[@title=\"Zoom out\"]";
    public static final String btn_Toggle_fullscreen = "//button[@title=\"Toggle fullscreen\"]";
    public static final String btn_hide_show_navbar = "//div[@title=\"Show/hide nav bar\"]";
    public static final String nav_bar ="//nav[@class=\"BRcontrols\"]"; 
    public static final String btn_drag_particular_page = "//span[@class=\"ui-slider-handle ui-corner-all ui-state-default\"]";
    public static final String lnk_map_atlas_services = "//a[text()=\"Map/Atlas Services\"]";
    public static final String lnk_Theme = "//a[text()=\"Themes\"]";
    public static final String lnk_OGC_Services = "//a[text()=\"OGC Services\"]";
    public static final String lnk_WMS_Services = "//a[text()=\"WMS Services\"]";
    public static final String lnk_NSA_adm = "//a[text()=\"NSA- Administrative\"]";
    public static final String lnk_About_Us = "//a[text()=\"About Us\"]";
    public static final String lnk_All = "//a[text()=\"All\"]";
    public static final String lnk_Adm_and_pol = "//a[text()=\"Administrative and Political\"]";
    public static final String lnk_particular_map = "//div[@class=\"view-content\"]/ul/li[2]/div";
    public static final String label_Map_Geoportal = "//div[@id=\"main-content\"]/div[2]";
    public static final String  txt_Search_Map_Atlas_Service = "//input[@placeholder=\"Search\"]";
    public static final String  ddm_sort_by = "//select[@name='sort_by']";
    public static final String  ddm_show_entries = "//select[@name='items_per_page']";
    public static final String btn_Apply ="//input[@value='Apply']";
    public static final String btn_Reset ="//input[@value='Reset']";
    public static final String btn_list_view="//a[@title='List View']";
    public static final String List_view="//li[@class=\"col-sm-4 list\"]";
    public static final String btn_Next_Page="//a[@title=\"Go to next page\"]";
    public static final String btn_Previous_Page="//a[@title=\"Go to previous page\"]";
    public static final String btn_Particular_Page="//a[@title=\"Go to page 7\"]";
    public static final String btn_last_Page="//a[@title=\"Go to last page\"]";
    public static final String btn_First_Page="//a[@title=\"Go to first page\"]";
    public static final String btn_Edit="//button[text()=\"Edit\"]";
    public static final String btn_Apply_FME="//button[text()=\"Apply\"]";
    public static final String btn_map_extent="//a[@title=\"Full Extent\"]";
    public static final String btn_Pan="//a[@title=\"Pan\"]";
    public static final String btn_Zoom_in_FME="//a[@title=\"Zoom In\"]";
    public static final String btn_Zoom_Out_FME="//a[@title=\"Pan\"]";
    public static final String btn_dashboard_collapse="//span[@class=\"mapoption-toggle\"]";
    public static final String btn_dashboard_expand="//span[@class=\"mapoption-toggle option-active\"]";
    public static final String dashboard_expand="//div[@class=\"right-header col-sm-12 view-config-0\"]";
    public static final String dashboard_collapse="//div[@class=\"right-header col-sm-12 view-config-0 open-right-option\"]";
    public static final String btn_pointer="//a[text()=\" Pointer\"]";
    public static final String btn_identify="//a[text()=\" Identify\"]";
    public static final String btn_pan="//a[text()=\" Pan\"]";
    public static final String btn_refresh="//a[text()=\" Refresh\"]";
    public static final String btn_zoom_features="//a[text()=\"Zoom\"]";
    public static final String btn_zoom_in_dashboard="//a[@title=\"Activate this tool to Zoom In\"]";
    public static final String btn_zoom_out_dashboard="//a[@title=\"Activate this tool to Zoom out\"]";
    public static final String btn_full_extent="//a[text()=\"Full Extent\"]";
    public static final String btn_label_International_Boundary_layer="//span[text()=\"International Boundary \"]";
    public static final String btn_swipe_features="//a[text()=\"Swipe\"]";
    public static final String btn_swipe_by_layer="//a[@title=\"Activate this tool to Swipe by Layer\"]";
    public static final String btn_ok_swipe_popup="//button[text()=\"OK\"]";
    public static final String btn_close_swipe_popup="//div[@class=\"x-tool x-tool-close\"]";
    public static final String dialog_swipe_popup="//div[@id=\"ext-comp-1073\"]";
    public static final String val_message_swipe_popup="//span[text()=\"Select Proper Layer Before Swipe Start\"]";
    public static final String btn_swipe_by_horizontal="//a[@title=\"Activate this tool to Swipe by Horizontal\"]";
    public static final String btn_swipe_by_pointer="//a[@title=\"Activate this tool to Swipe by Pointer\"]";
    public static final String btn_Coordinates="//a[text()=\" Coordinates\"]";
    public static final String txt_long_d="//input[@id=\"txt_long_d\"]";
    public static final String txt_long_m="//input[@id=\"txt_long_m\"]";
    public static final String txt_long_s="//input[@id=\"txt_long_s\"]";
    public static final String txt_lat_d="//input[@id=\"txt_lat_d\"]";
    public static final String txt_lat_m="//input[@id=\"txt_lat_m\"]";
    public static final String txt_lat_s="//input[@id=\"txt_lat_s\"]";
    public static final String ddm_zoom="//select[@id=\"ddlgtcscalevalue\"]";
    public static final String chk_remember_loc="//input[@id=\"chk_remember_loc\"]";
    public static final String chk_gtc_clear_marker="//input[@id=\"chk_gtc_clear_marker\"]";
    public static final String btn_gtc_go="//button[@id=\"btn_gtc_go\"]";
    public static final String img_Pin_point="//div/div[1]/img[@class=\"olAlphaImg\"]";
    public static final String btn_rm_marker="//button[@id=\"btn_rm_marker\"]";
    public static final String chk_latlonl="//input[@id=\"latlon\"]";
    public static final String txt_long_grad="//input[@id=\"txt_long_grad\"]";
    public static final String txt_lat_grad="//input[@id=\"txt_lat_grad\"]";
    public static final String btn_latlon_go="//button[@id=\"btn_latlon_go\"]";
    public static final String btn_collapase_GTC="//body/div[@class=\"ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-draggable two-column coordinatepopup\"]/div/button[@title=\"collapse\" and text()=\"collapse\"]";
    public static final String btn_expand_GTC="//body/div[@class=\"ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-draggable two-column coordinatepopup\"]/div/button[@title=\"restore\" and text()=\"restore\"]";
    public static final String btn_close_GTC="//body/div[@class=\"ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-draggable two-column coordinatepopup\"]/div/button[@title=\"Close\" and text()=\"Close\"]";
    public static final String val_message_GTC="//label[text()=\"Please enter valid value in DMS\"]";
    public static final String btn_measure_features="//a[text()=\"Measure\"]";
    public static final String btn_Length="//a[@title=\"Activate this tool to Measure Line Length\"]";
    public static final String chk_foot_mile="//div/div[1]/input[@name=\"measurementunit\"]";
    public static final String polyline="//*[name()=\"svg\"]/*[name()=\"g\"]/*[name()=\"g\"]/*[name()=\"polyline\"]";
    public static final String btn_Area="//a[@title=\"Activate this tool to Measure Area\"]";
    public static final String polygone="//*[name()=\"svg\"]/*[name()=\"g\"]/*[name()=\"g\"]/*[name()=\"path\"]";
    public static final String chk_Sqmeter_Sqkm="//div/div[2]/input[@name=\"measurementunit\"]";
    public static final String btn_Set_Scale="//a[@title=\"Zoom to particular scale directly\"]";
    public static final String ddm_Custom_Scale="//select[@id=\"ddluserscale\"]";
    public static final String txt_Define_Scale="//input[@id=\"ddlscaletext\"]";
    public static final String btn_Go_Scale="//input[@id=\"userdefinezoombtn\"]";
    public static final String btn_Close_SS ="//body/div[@class=\"ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-draggable single-column\"]/div/button[@title=\"Close\" and text()=\"Close\"]";
    public static final String btn_Draw_Points="//div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Draw Points\"]";
    public static final String circle="//*[name()=\"svg\"]/*[name()=\"g\"]/*[name()=\"g\"]/*[name()=\"circle\"]";
    public static final String btn_Draw_line="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Draw Line\"]";
    public static final String btn_Draw_polygon="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Draw Polygon\"]";
    public static final String btn_Draw_text_label="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Draw Text Label\"]";
    public static final String txt_Attribute_label ="//input[@id=\"olLabelInput\"]";
    public static final String btn_Modify_Geometry="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Modify Geometry\"]";
    public static final String btn_Clip="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Clip\"]";
    public static final String btn_Select_Geometry="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Select Geometry\"]";
    public static final String btn_Drag_Geometry="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Drag Geometry\"]";
    public static final String btn_Delete_selected_Geometry="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Delete Selected Geometries\"]";
    public static final String btn_Delete_All_Geometry="//div/div[@class=\"olEditorControlEditorPanel olControlNoSelect\"]/div[@title=\"Delete all Geometries\"]";
    public static final String btn_Grid_On_Off = "//a[@title=\"On/Off Graticule\"]";
    public static final String Grid_Lines = "//*[name()=\"svg\"]/*[name()=\"g\"]/*[name()=\"g\"]/*[name()=\"text\"]";
    public static final String btn_Query_Builder = "//a[@title=\"Build custom query to find data\"]";
    public static final String ddl_Target_Layer = "//span[text()=\"-- Select Layer--\" and @id=\"select2-ddl_query_layers-container\"]";
    public static final String btn_Apply_QB = "//button[text()=\"Apply\"]";
    public static final String btn_Clear_QB = "//button[text()=\"Clear\"]";
    public static final String radio_attrqur = "//input[@id=\"attrqur\"]";
    public static final String radio_within = "//input[@id=\"within\"]";
    public static final String radio_Intersects = "//input[@id=\"intersacts\"]";
    public static final String ddl_spatial_layers = "//span[text()=\"-- Select Layer--\" and @id=\"select2-ddl_spatial_layers-container\"]";
    public static final String txt_buffer = "//input[@id=\"txt_spatial_buffer\"]";
    public static final String btn_collapse_QB="//div[@aria-describedby=\"includedQuerybuilderView\"]/div/button[text()=\"collapse\"]";
    public static final String btn_expand_QB="//div[@aria-describedby=\"includedQuerybuilderView\"]/div/button[2]";
    public static final String btn_close_QB="//div[@aria-describedby=\"includedQuerybuilderView\"]/div/button[text()=\"Close\"]";
    public static final String btn_next_QB="//a[text()=\"Next\"]";
    public static final String btn_previous_QB="//a[text()=\"Previous\"]";
    public static final String btn_3_page_QB="//a[text()=\"3\"]";
    public static final String btn_create_My_Map = "//a[@title=\"On the fly map creation\"]";
    public static final String btn_Upload_CSV = "//input[@type=\"file\" and @accept=\".csv\"]";
    public static final String btn_Apply_CMP = "//div[@id=\"tabs-csv\"]/div/div/button[@id=\"btn_apply_otfmc\"]";
    public static final String btn_Clear_CMP = "//div[@id=\"tabs-csv\"]/div/div/button[@id=\"btn_otfmc_clear\"]";
    public static final String btn_Download_CSV = "//div[@id=\"tabs-csv\"]/div/div/button[@id=\"btn_otfmc_download_csv\"]";
    public static final String btn_collapse_CMP="//div[@aria-labelledby=\"ui-id-10\"]/div/button[@title=\"collapse\"]";
    public static final String btn_expand_CMP="//div[@aria-labelledby=\"ui-id-10\"]/div/button[text()=\"restore\"]";
    public static final String btn_close_CMP="//div[@aria-labelledby=\"ui-id-10\"]/div/button[@title=\"Close\"]";
    public static final String btn_Elevation_profile = "//a[@title=\"Create Elevation Profile\"]";
    public static final String btn_draw_EP = "//li/div/div[2]";
    public static final String btn_collapse_EP="//div[@aria-labelledby=\"ui-id-3\"]/div/button[@title=\"collapse\"]";
    public static final String btn_expand_EP="//div[@aria-labelledby=\"ui-id-3\"]/div/button[text()=\"restore\"]";
    public static final String btn_close_EP="//div[@aria-labelledby=\"ui-id-3\"]/div/button[@title=\"Close\"]";
    public static final String btn_collapse_Legend="//div[@aria-describedby=\"includeLegendWindow\"]/div/button[@title=\"collapse\"]";
    public static final String btn_expand_Legend="//div[@aria-describedby=\"includeLegendWindow\"]/div/button[text()=\"restore\"]";
    public static final String btn_close_Legend="//div[@aria-describedby=\"includeLegendWindow\"]/div/button[@title=\"Close\"]";
}

